### ISSUE TITLE
Incorrect color for nano (light grey?)

### ISSUE THREAD

**Issue by WoodyWoodsta** [dperrera/hyperterm-material#1]
Unfortunate choice of color for the nano header and keyboard shortcuts as can be seen in the screenshot. Other themes appear have light grey for this color :+1: 

![image](https://cloud.githubusercontent.com/assets/8268040/16907117/d9d9fc3c-4cc0-11e6-8bae-829dc258199a.png)

Otherwise this is my favourite theme by a long way :+1:

**Comment by dperrera** [comment]
@WoodyWoodsta Thanks for filing that issue. It's fixed in 0.1.2.

**Comment by WoodyWoodsta** [comment]
Having a similar issue again on Hyper 0.8.2. This time the text is the incorrect color - not sure if this is an upstream bug or not.

![screenshot from 2016-10-18 09 14 53](https://cloud.githubusercontent.com/assets/8268040/19467788/6e7755ac-9513-11e6-85b9-84ba2d35c9f4.png)

**Comment by dperrera** [comment]
It looks like the white background is unassigned in hyper itself. Check out [this issue on the main project](https://github.com/zeit/hyper/issues/883) for a potential (and hopefully temporary) fix.
