### ISSUE TITLE
Empty space top-left when fullscreen

### ISSUE THREAD

**Issue by wilsonpage** [dperrera/hyperterm-material#2]
When fullscreen the button in the top-left are no longer present, but there is a still space reserved for them. This may be an issue with Hyperterm and not this them, unsure :)

![screen shot 2016-07-18 at 10 09 21](https://cloud.githubusercontent.com/assets/1020551/16910299/d66def68-4ccf-11e6-9f0e-8ea23133337e.png)

**Comment by dperrera** [comment]
@wilsonpage That's a Hyperterm issue and it looks like someone already [reported the bug](https://github.com/zeit/hyperterm/issues/151). This theme really emphasizes the issue!
