### ISSUE TITLE
Error/Warning messages are hard to read

### ISSUE THREAD

**Issue by MaxGiting** [dperrera/hyperterm-material#3]
Error messages with a red background and a light font colour are hard to read.

![screen shot 2016-07-21 at 09 44 24](https://cloud.githubusercontent.com/assets/9828591/17016695/276474be-4f28-11e6-9d2f-fdcf6ecce91e.png)

**Comment by dperrera** [comment]
Fixed in 0.1.3. Thanks for reporting the bug!
